server:
  port: 8888
spring:
  datasource:
    url: jdbc:mysql://x:3306/remind?useUnicode=true&amp&serverTimezone=Asia/Shanghai
    username: x
    password: x
    driver-class-name: com.mysql.cj.jdbc.Driver
ding:
  ding-url: https://oapi.dingtalk.com/robot/send?access_token=x
  keyword: x
